// Generated by IcedCoffeeScript 1.7.1-b
(function() {
  var log, to_percent, _,
    __slice = [].slice;

  _ = require('lodash');

  log = function() {
    var x;
    x = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return console.log.apply(console, x);
  };

  module.exports = to_percent = function(obj, decimals) {
    var k, percent, total, v;
    if (decimals == null) {
      decimals = 1;
    }
    if (!_.size(obj)) {
      return obj;
    }
    total = _.sum(_.values(obj));
    for (k in obj) {
      v = obj[k];
      percent = ((v / total) * 100).toFixed(decimals);
      obj[k] = percent;
    }
    return obj;
  };


  /*
  if !module.parent
    log to_percent({
      safari: 100
      chrome: 5
      msie: 10
    })
   */

}).call(this);
